### ISSUE TITLE
Unable to import package

### ISSUE THREAD

**Issue by hansputera** [ilhamjaya08/samp-query-ts#1]
Hi Ilham, can you upload the compiled scripts into npmjs? We unable to import your package and use it directly.
![image](https://github.com/ilhamjaya08/samp-query-ts/assets/47862061/56c8e058-e0fd-4286-baf3-cf0b323e2b11)

![image](https://github.com/ilhamjaya08/samp-query-ts/assets/47862061/51d2df87-cd82-4865-a81b-e995fb3cd477)

Thank you!

**Comment by ilhamjaya08** [comment]
The library version available here is outdated and deprecated, while the latest version is still in my development but still stalled, I will work on it as soon as possible. I will also make the latest version compatible with the OpenMP version (Development of a GTA:SA multiplayer mod that is compatible with SA:MP).
If you want to contribute, I welcome you to contact me first for communication.
FYI, this package was uploaded to npmjs since I released it, here is the link https://www.npmjs.com/package/samp-query-ts

**Comment by ilhamjaya08** [comment]
At least I will soon make an example script for examples of the use/application of this library. Thank you for your suggestion!

**Comment by hansputera** [comment]
> The library version available here is outdated and deprecated, while the latest version is still in my development but still stalled, I will work on it as soon as possible. I will also make the latest version compatible with the OpenMP version (Development of a GTA:SA multiplayer mod that is compatible with SA:MP). If you want to contribute, I welcome you to contact me first for communication. FYI, this package was uploaded to npmjs since I released it, here is the link https://www.npmjs.com/package/samp-query-ts

Hi, thanks for response. Maybe you can see the fork I just made? https://github.com/hansputera/samp-query-ts

The first problem when I tested this project was that we couldn't receive any packets from the UDP server. Once I looked at the documentation on https://sampwiki.blast.hk/wiki/Query_Mechanism, and rewrote + tested it with a registered server on OpenMP (open.mp), it worked (~2x faster)

**Comment by ilhamjaya08** [comment]
whoa, thanks for your effort for create the stable version, if u wanna sync with this original repo, create a PR and i will accept it!

**Comment by hansputera** [comment]
https://github.com/ilhamjaya08/samp-query-ts/pull/2

> whoa, thanks for your effort for create the stable version, if u wanna sync with this original repo, create a PR and i will accept it!

**Comment by ilhamjaya08** [comment]
Issue closed with problem solve and PR from @hansputera and @Rezky23
